name: Stitcher unit tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm --filter "stitcher" install

  # Test job
  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Run unit tests
        run: pnpm --filter "stitcher" test
