name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  stitcher:
    runs-on: ubuntu-latest
    name: Stitcher
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm --filter "stitcher" install
      - name: Run unit tests
        run: pnpm --filter "stitcher" test
